services:
  - type: web
    name: refrr-frontend
    env: node
    buildCommand: cd frontend && npm install && TSC_COMPILE_ON_ERROR=true npm run build
    startCommand: cd frontend && NODE_ENV=production node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: REACT_APP_API_URL
        value: "https://refrr-backend.onrender.com"
      - key: CI
        value: "true"
      - key: DISABLE_ESLINT_PLUGIN
        value: "true"
      - key: GENERATE_SOURCEMAP
        value: "false"
      - key: SKIP_PREFLIGHT_CHECK
        value: "true"
      - key: TSC_COMPILE_ON_ERROR
        value: "true"
    healthCheckPath: /health
    autoDeploy: true
    plan: free

  - type: web
    name: refrr-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && NODE_ENV=production npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: NPM_CONFIG_AUDIT
        value: "false"
      - key: NPM_CONFIG_FUND
        value: "false"
    healthCheckPath: /api/health
    autoDeploy: true
    plan: free 