services:
  - type: web
    name: refrr-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://refrr.onrender.com
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.x
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true

  - type: web
    name: refrr-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true 