services:
  - type: web
    name: refrr-frontend
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=256 --max-semi-space-size=64 --optimize-for-size
      - key: CI
        value: "true"
      - key: DISABLE_ESLINT_PLUGIN
        value: "true"
      - key: GENERATE_SOURCEMAP
        value: "false"
      - key: SKIP_PREFLIGHT_CHECK
        value: "true"
      - key: PORT
        value: "3000"
      - key: REACT_APP_API_URL
        value: "https://refrr.onrender.com"
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: NPM_CONFIG_AUDIT
        value: "false"
      - key: NPM_CONFIG_FUND
        value: "false"
    healthCheckPath: /
    autoDeploy: true
    plan: free

  - type: web
    name: refrr-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=256 --optimize-for-size
      - key: PORT
        value: "10000"
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: NPM_CONFIG_AUDIT
        value: "false"
      - key: NPM_CONFIG_FUND
        value: "false"
    healthCheckPath: /api/health
    autoDeploy: true
    plan: free 