services:
  - type: web
    name: refrr-frontend
    env: node
    buildCommand: chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: REACT_APP_API_URL
        value: https://refrr.onrender.com
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.x
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true

  - type: web
    name: refrr-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true 