services:
  - type: web
    name: refrr-frontend
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=256 --max-semi-space-size=64
      - key: CI
        value: "true"
      - key: DISABLE_ESLINT_PLUGIN
        value: "true"
      - key: GENERATE_SOURCEMAP
        value: "false"
      - key: SKIP_PREFLIGHT_CHECK
        value: "true"
    healthCheckPath: /
    autoDeploy: true
    plan: free

  - type: web
    name: refrr-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=256
    healthCheckPath: /api/health
    autoDeploy: true
    plan: free 