name: Simple Deploy

on:
  push:
    branches: [ main ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Information
        run: |
          echo "GitHub Event: ${{ github.event_name }}"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "GitHub SHA: ${{ github.sha }}"
          echo "GitHub Actor: ${{ github.actor }}"
          echo "GitHub Repository: ${{ github.repository }}"
          echo "GitHub Workspace: ${{ github.workspace }}"
          
  build:
    needs: debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd frontend
          npm install
          
      - name: Build
        run: |
          cd frontend
          npm run build
        env:
          REACT_APP_API_URL: ${{ secrets.API_URL }}
          
      - name: Deploy
        run: |
          echo "Starting deployment..."
          echo "Current directory: $(pwd)"
          echo "Frontend directory contents:"
          ls -la frontend/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 