name: Basic Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Debug Repository
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Frontend directory contents:"
          ls -la frontend || echo "Frontend directory not found"
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          if [ -d "frontend" ]; then
            cd frontend
            echo "Installing dependencies..."
            npm install || echo "npm install failed"
            echo "npm version:"
            npm --version
          else
            echo "Error: frontend directory not found"
            exit 1
          fi
          
      - name: Build
        run: |
          if [ -d "frontend" ]; then
            cd frontend
            echo "Building application..."
            npm run build || echo "Build failed"
            echo "Build directory contents:"
            ls -la build || echo "Build directory not found"
          else
            echo "Error: frontend directory not found"
            exit 1
          fi
          
      - name: List Build Files
        run: |
          echo "Build directory contents:"
          ls -la frontend/build
        
      - name: Print Hello
        run: echo "Hello World"
        
      - name: List Files
        run: ls -la 