name: Basic Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd frontend
          npm install
          
      - name: Build
        run: |
          cd frontend
          npm run build
          
      - name: List Build Files
        run: |
          echo "Build directory contents:"
          ls -la frontend/build
        
      - name: Print Hello
        run: echo "Hello World"
        
      - name: List Files
        run: ls -la 